# Generated by Django 4.0.3 on 2022-03-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_rename_apelldio_administradores_apellido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id',
        ),
        migrations.AddField(
            model_name='usuario',
            name='nick',
            field=models.CharField(default=1, max_length=15, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
