# Generated by Django 4.0.3 on 2022-03-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_remove_usuario_id_usuario_nick'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nick',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
