# Generated by Django 4.0.3 on 2022-03-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_remove_usuario_nick_alter_usuario_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administradores',
            name='id',
        ),
        migrations.AddField(
            model_name='blogs',
            name='contenido',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='creacion',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='administradores',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
