# Generated by Django 4.0.3 on 2022-03-27 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_productos_delete_blogs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='nombre',
            new_name='producto',
        ),
    ]
