# Generated by Django 4.0.3 on 2022-04-13 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_alter_productos_precio_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
    ]
