# Generated by Django 4.0.3 on 2022-04-13 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_remove_message_sender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
