# Generated by Django 4.0.3 on 2022-04-18 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0030_alter_redessociales_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
