# Generated by Django 4.0.3 on 2022-04-23 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0034_delete_redessociales'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administradores',
        ),
        migrations.DeleteModel(
            name='productos',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
