# Generated by Django 4.0.3 on 2022-04-16 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applogin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, default='/media/avatars/descarga_14GP6TQ.jpg', null=True, upload_to='avatars'),
        ),
    ]
