# Generated by Django 4.0.3 on 2022-04-16 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applogin', '0005_alter_avatar_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(default='/media/avatars/descarga_14GP6TQ.jpg', upload_to='avatars'),
        ),
    ]
