# Generated by Django 4.0.3 on 2022-04-20 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applogin', '0009_delete_redessociales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(default='avatars/no-avatar.png', upload_to='avatars'),
        ),
    ]
