# Generated by Django 4.0.3 on 2022-04-18 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Applogin', '0008_alter_avatar_imagen_redessociales'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RedesSociales',
        ),
    ]
