# Generated by Django 4.0.3 on 2022-04-20 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applogin', '0010_alter_avatar_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(default='no-avatar.png', upload_to='avatars'),
        ),
    ]
