# Generated by Django 4.0.3 on 2022-04-22 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applogin', '0016_alter_redessociales_facebook_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redessociales',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='redessociales',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='redessociales',
            name='twitter',
        ),
        migrations.AddField(
            model_name='redessociales',
            name='pagina',
            field=models.URLField(blank=True, null=True),
        ),
    ]
