# Generated by Django 4.0.3 on 2022-03-26 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administradores',
            old_name='apelldio',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='apelldio',
            new_name='apellido',
        ),
    ]
