# Generated by Django 4.0.3 on 2022-03-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_remove_administradores_id_blogs_contenido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('creador', models.CharField(max_length=40)),
                ('contenido', models.CharField(max_length=1000)),
                ('creacion', models.DateField(auto_now=True)),
            ],
        ),
    ]
