# Generated by Django 4.0.3 on 2022-04-15 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_alter_blog_creador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='creador',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
