# Generated by Django 4.0.3 on 2022-04-15 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0023_blog_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='imagen',
        ),
    ]
