# Generated by Django 4.0.3 on 2022-04-16 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0025_blog_foto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
