# Generated by Django 4.0.3 on 2022-04-18 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0031_blog_subtitulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='subtitulo',
            field=models.CharField(max_length=40),
        ),
    ]
