# Generated by Django 4.0.3 on 2022-04-20 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0033_alter_blog_contenido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RedesSociales',
        ),
    ]
