# Generated by Django 4.0.3 on 2022-04-26 22:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0035_delete_administradores_delete_productos_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mensajerias',
            new_name='Mensajes',
        ),
    ]
